/* Generated By:JJTree: Do not edit this line. _Expression.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=_,NODE_EXTENDS=,NODE_FACTORY= */
package com.infoscient.proteus.modelica.calculator;

import java.util.LinkedList;
import java.util.List;

public class _Expression extends SimpleNode {
	public double val;
	
	public List<_Term> termList = new LinkedList<_Term>();

	public _Expression(int id) {
		super(id);
	}

	public _Expression(Calculator p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CalculatorVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
