/* Generated By:JJTree: Do not edit this line. _Expressions.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=_,NODE_EXTENDS=,NODE_FACTORY= */
package com.infoscient.proteus.modelica.calculator;

import java.util.LinkedList;
import java.util.List;

public class _Expressions extends SimpleNode {
	public List<_Expression> valueList = new LinkedList<_Expression>();

	public _Expressions(int id) {
		super(id);
	}

	public _Expressions(Calculator p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CalculatorVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=8bf1dc121ded76e700e4c97fdfd50bd2 (do not edit this
 * line)
 */
