/* Generated By:JJTree: Do not edit this line. _Functions.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=_,NODE_EXTENDS=,NODE_FACTORY= */
package com.infoscient.proteus.modelica.calculator;

import java.util.HashMap;
import java.util.Map;

import com.infoscient.proteus.modelica.DoubleRecord;

public class _Functions extends SimpleNode {
	public Map<String, DoubleRecord> varList = new HashMap<String, DoubleRecord>();
  public _Functions(int id) {
    super(id);
  }

  public _Functions(Calculator p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(CalculatorVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ea482a4e56a8372774ce9a8cdaab9ba6 (do not edit this line) */
