/* Generated By:JJTree: Do not edit this line. _Variables.java Version 4.1 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=_,NODE_EXTENDS=,NODE_FACTORY= */
package com.infoscient.proteus.modelica.calculator;

import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

import com.infoscient.proteus.modelica.DoubleRecord;

public class _Variables extends SimpleNode {
	public Map<String, DoubleRecord> varList = new HashMap<String, DoubleRecord>();

	public _Variables(int id) {
		super(id);
	}

	public _Variables(Calculator p, int id) {
		super(p, id);
	}

	/** Accept the visitor. **/
	public Object jjtAccept(CalculatorVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
/*
 * JavaCC - OriginalChecksum=975e8789890e13e61039491a2c5cab19 (do not edit this
 * line)
 */
