/* Generated By:JavaCC: Do not edit this line. CalculatorVisitor.java Version 4.1d1 */
package com.infoscient.proteus.modelica.calculator;

public interface CalculatorVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(_Variables node, Object data);
  public Object visit(_Functions node, Object data);
  public Object visit(_Start node, Object data);
  public Object visit(_Expressions node, Object data);
  public Object visit(_Expression node, Object data);
  public Object visit(_Term node, Object data);
  public Object visit(_Primary node, Object data);
}
/* JavaCC - OriginalChecksum=a503779ee5daca003e3ad902b3d8714b (do not edit this line) */
