/* Generated By:JavaCC: Do not edit this line. CalculatorTreeConstants.java Version 4.1d1 */
package com.infoscient.proteus.modelica.calculator;

public interface CalculatorTreeConstants
{
  public int JJTVARIABLES = 0;
  public int JJTFUNCTIONS = 1;
  public int JJTSTART = 2;
  public int JJTEXPRESSIONS = 3;
  public int JJTEXPRESSION = 4;
  public int JJTTERM = 5;
  public int JJTPRIMARY = 6;


  public String[] jjtNodeName = {
    "Variables",
    "Functions",
    "Start",
    "Expressions",
    "Expression",
    "Term",
    "Primary",
  };
}
/* JavaCC - OriginalChecksum=f470a138d2ebd1ab12e37298f8e9139a (do not edit this line) */
