/* Generated By:JJTree: Do not edit this line. .\ModelicaParserVisitor.java */

package proteus.gwt.shared.modelica;

import proteus.gwt.shared.modelica.parser.ModelicaParserVisitor;
import proteus.gwt.shared.modelica.parser.OMAlgorithmSection;
import proteus.gwt.shared.modelica.parser.OMAnnotation;
import proteus.gwt.shared.modelica.parser.OMArgument;
import proteus.gwt.shared.modelica.parser.OMArgumentList;
import proteus.gwt.shared.modelica.parser.OMArithmeticExpression;
import proteus.gwt.shared.modelica.parser.OMClassDefinition;
import proteus.gwt.shared.modelica.parser.OMClassModification;
import proteus.gwt.shared.modelica.parser.OMClassSpecifier;
import proteus.gwt.shared.modelica.parser.OMComment;
import proteus.gwt.shared.modelica.parser.OMComponentClause;
import proteus.gwt.shared.modelica.parser.OMComponentClause1;
import proteus.gwt.shared.modelica.parser.OMComponentDecl;
import proteus.gwt.shared.modelica.parser.OMComponentDecl1;
import proteus.gwt.shared.modelica.parser.OMComponentList;
import proteus.gwt.shared.modelica.parser.OMComponentRef;
import proteus.gwt.shared.modelica.parser.OMComposition;
import proteus.gwt.shared.modelica.parser.OMCondAttr;
import proteus.gwt.shared.modelica.parser.OMConnectClause;
import proteus.gwt.shared.modelica.parser.OMConstrainingClause;
import proteus.gwt.shared.modelica.parser.OMDeclaration;
import proteus.gwt.shared.modelica.parser.OMElement;
import proteus.gwt.shared.modelica.parser.OMElementList;
import proteus.gwt.shared.modelica.parser.OMElementModification;
import proteus.gwt.shared.modelica.parser.OMElementModificationOrReplaceable;
import proteus.gwt.shared.modelica.parser.OMElementRedeclaration;
import proteus.gwt.shared.modelica.parser.OMElementReplaceable;
import proteus.gwt.shared.modelica.parser.OMEnumList;
import proteus.gwt.shared.modelica.parser.OMEnumLiteral;
import proteus.gwt.shared.modelica.parser.OMEquation;
import proteus.gwt.shared.modelica.parser.OMEquationSection;
import proteus.gwt.shared.modelica.parser.OMExpression;
import proteus.gwt.shared.modelica.parser.OMExtendsClause;
import proteus.gwt.shared.modelica.parser.OMExternalFuncCall;
import proteus.gwt.shared.modelica.parser.OMFactor;
import proteus.gwt.shared.modelica.parser.OMForEquation;
import proteus.gwt.shared.modelica.parser.OMForIndex;
import proteus.gwt.shared.modelica.parser.OMForIndices;
import proteus.gwt.shared.modelica.parser.OMForStatement;
import proteus.gwt.shared.modelica.parser.OMFunctionArguments;
import proteus.gwt.shared.modelica.parser.OMFunctionCallArgs;
import proteus.gwt.shared.modelica.parser.OMIfEquation;
import proteus.gwt.shared.modelica.parser.OMIfStatement;
import proteus.gwt.shared.modelica.parser.OMImportClause;
import proteus.gwt.shared.modelica.parser.OMLogicalExpression;
import proteus.gwt.shared.modelica.parser.OMLogicalFactor;
import proteus.gwt.shared.modelica.parser.OMLogicalTerm;
import proteus.gwt.shared.modelica.parser.OMModification;
import proteus.gwt.shared.modelica.parser.OMNamedArgument;
import proteus.gwt.shared.modelica.parser.OMPrimary;
import proteus.gwt.shared.modelica.parser.OMRelation;
import proteus.gwt.shared.modelica.parser.OMSimpleExpression;
import proteus.gwt.shared.modelica.parser.OMStatement;
import proteus.gwt.shared.modelica.parser.OMStoredDefinition;
import proteus.gwt.shared.modelica.parser.OMSubscript;
import proteus.gwt.shared.modelica.parser.OMTerm;
import proteus.gwt.shared.modelica.parser.OMTypePrefix;
import proteus.gwt.shared.modelica.parser.OMWhenEquation;
import proteus.gwt.shared.modelica.parser.OMWhenStatement;
import proteus.gwt.shared.modelica.parser.OMWhileStatement;
import proteus.gwt.shared.modelica.parser.SimpleNode;

public class ModelicaParserVisitorAdapter implements ModelicaParserVisitor {

	public Object visit(SimpleNode node, Object data) {
		return null;
	}

	public Object visit(OMStoredDefinition node, Object data) {
		return null;
	}

	public Object visit(OMClassDefinition node, Object data) {
		return null;
	}

	public Object visit(OMClassSpecifier node, Object data) {
		return null;
	}

	public Object visit(OMEnumList node, Object data) {
		return null;
	}

	public Object visit(OMEnumLiteral node, Object data) {
		return null;
	}

	public Object visit(OMComposition node, Object data) {
		return null;
	}

	public Object visit(OMExternalFuncCall node, Object data) {
		return null;
	}

	public Object visit(OMElementList node, Object data) {
		return null;
	}

	public Object visit(OMElement node, Object data) {
		return null;
	}

	public Object visit(OMImportClause node, Object data) {
		return null;
	}

	public Object visit(OMExtendsClause node, Object data) {
		return null;
	}

	public Object visit(OMConstrainingClause node, Object data) {
		return null;
	}

	public Object visit(OMComponentClause node, Object data) {
		return null;
	}

	public Object visit(OMTypePrefix node, Object data) {
		return null;
	}

	public Object visit(OMComponentList node, Object data) {
		return null;
	}

	public Object visit(OMComponentDecl node, Object data) {
		return null;
	}

	public Object visit(OMCondAttr node, Object data) {
		return null;
	}

	public Object visit(OMDeclaration node, Object data) {
		return null;
	}

	public Object visit(OMModification node, Object data) {
		return null;
	}

	public Object visit(OMClassModification node, Object data) {
		return null;
	}

	public Object visit(OMArgumentList node, Object data) {
		return null;
	}

	public Object visit(OMArgument node, Object data) {
		return null;
	}

	public Object visit(OMElementModificationOrReplaceable node, Object data) {
		return null;
	}

	public Object visit(OMElementModification node, Object data) {
		return null;
	}

	public Object visit(OMElementRedeclaration node, Object data) {
		return null;
	}

	public Object visit(OMElementReplaceable node, Object data) {
		return null;
	}

	public Object visit(OMComponentClause1 node, Object data) {
		return null;
	}

	public Object visit(OMComponentDecl1 node, Object data) {
		return null;
	}

	public Object visit(OMEquationSection node, Object data) {
		return null;
	}

	public Object visit(OMAlgorithmSection node, Object data) {
		return null;
	}

	public Object visit(OMEquation node, Object data) {
		return null;
	}

	public Object visit(OMStatement node, Object data) {
		return null;
	}

	public Object visit(OMIfEquation node, Object data) {
		return null;
	}

	public Object visit(OMIfStatement node, Object data) {
		return null;
	}

	public Object visit(OMForEquation node, Object data) {
		return null;
	}

	public Object visit(OMForStatement node, Object data) {
		return null;
	}

	public Object visit(OMForIndices node, Object data) {
		return null;
	}

	public Object visit(OMForIndex node, Object data) {
		return null;
	}

	public Object visit(OMWhileStatement node, Object data) {
		return null;
	}

	public Object visit(OMWhenEquation node, Object data) {
		return null;
	}

	public Object visit(OMWhenStatement node, Object data) {
		return null;
	}

	public Object visit(OMConnectClause node, Object data) {
		return null;
	}

	public Object visit(OMExpression node, Object data) {
		return null;
	}

	public Object visit(OMSimpleExpression node, Object data) {
		return null;
	}

	public Object visit(OMLogicalExpression node, Object data) {
		return null;
	}

	public Object visit(OMLogicalTerm node, Object data) {
		return null;
	}

	public Object visit(OMLogicalFactor node, Object data) {
		return null;
	}

	public Object visit(OMRelation node, Object data) {
		return null;
	}

	public Object visit(OMArithmeticExpression node, Object data) {
		return null;
	}

	public Object visit(OMTerm node, Object data) {
		return null;
	}

	public Object visit(OMFactor node, Object data) {
		return null;
	}

	public Object visit(OMPrimary node, Object data) {
		return null;
	}

	public Object visit(OMComponentRef node, Object data) {
		return null;
	}

	public Object visit(OMFunctionCallArgs node, Object data) {
		return null;
	}

	public Object visit(OMFunctionArguments node, Object data) {
		return null;
	}

	public Object visit(OMNamedArgument node, Object data) {
		return null;
	}

	public Object visit(OMSubscript node, Object data) {
		return null;
	}

	public Object visit(OMComment node, Object data) {
		return null;
	}

	public Object visit(OMAnnotation node, Object data) {
		return null;
	}
}
