/* Generated By:JavaCC: Do not edit this line. ModelicaParserTreeConstants.java Version 4.1d1 */
package com.infoscient.proteus.modelica.parser;

public interface ModelicaParserTreeConstants
{
  public int JJTSTOREDDEFINITION = 0;
  public int JJTCLASSDEFINITION = 1;
  public int JJTCLASSSPECIFIER = 2;
  public int JJTVOID = 3;
  public int JJTENUMLIST = 4;
  public int JJTENUMLITERAL = 5;
  public int JJTCOMPOSITION = 6;
  public int JJTEXTERNALFUNCCALL = 7;
  public int JJTELEMENTLIST = 8;
  public int JJTELEMENT = 9;
  public int JJTIMPORTCLAUSE = 10;
  public int JJTEXTENDSCLAUSE = 11;
  public int JJTCONSTRAININGCLAUSE = 12;
  public int JJTCOMPONENTCLAUSE = 13;
  public int JJTTYPEPREFIX = 14;
  public int JJTCOMPONENTLIST = 15;
  public int JJTCOMPONENTDECL = 16;
  public int JJTCONDATTR = 17;
  public int JJTDECLARATION = 18;
  public int JJTMODIFICATION = 19;
  public int JJTCLASSMODIFICATION = 20;
  public int JJTARGUMENTLIST = 21;
  public int JJTARGUMENT = 22;
  public int JJTELEMENTMODIFICATIONORREPLACEABLE = 23;
  public int JJTELEMENTMODIFICATION = 24;
  public int JJTELEMENTREDECLARATION = 25;
  public int JJTELEMENTREPLACEABLE = 26;
  public int JJTCOMPONENTCLAUSE1 = 27;
  public int JJTCOMPONENTDECL1 = 28;
  public int JJTEQUATIONSECTION = 29;
  public int JJTALGORITHMSECTION = 30;
  public int JJTEQUATION = 31;
  public int JJTSTATEMENT = 32;
  public int JJTIFEQUATION = 33;
  public int JJTIFSTATEMENT = 34;
  public int JJTFOREQUATION = 35;
  public int JJTFORSTATEMENT = 36;
  public int JJTFORINDICES = 37;
  public int JJTFORINDEX = 38;
  public int JJTWHILESTATEMENT = 39;
  public int JJTWHENEQUATION = 40;
  public int JJTWHENSTATEMENT = 41;
  public int JJTCONNECTCLAUSE = 42;
  public int JJTEXPRESSION = 43;
  public int JJTSIMPLEEXPRESSION = 44;
  public int JJTLOGICALEXPRESSION = 45;
  public int JJTLOGICALTERM = 46;
  public int JJTLOGICALFACTOR = 47;
  public int JJTRELATION = 48;
  public int JJTARITHMETICEXPRESSION = 49;
  public int JJTTERM = 50;
  public int JJTFACTOR = 51;
  public int JJTPRIMARY = 52;
  public int JJTCOMPONENTREF = 53;
  public int JJTFUNCTIONCALLARGS = 54;
  public int JJTFUNCTIONARGUMENTS = 55;
  public int JJTNAMEDARGUMENT = 56;
  public int JJTSUBSCRIPT = 57;
  public int JJTCOMMENT = 58;
  public int JJTANNOTATION = 59;


  public String[] jjtNodeName = {
    "StoredDefinition",
    "ClassDefinition",
    "ClassSpecifier",
    "void",
    "EnumList",
    "EnumLiteral",
    "Composition",
    "ExternalFuncCall",
    "ElementList",
    "Element",
    "ImportClause",
    "ExtendsClause",
    "ConstrainingClause",
    "ComponentClause",
    "TypePrefix",
    "ComponentList",
    "ComponentDecl",
    "CondAttr",
    "Declaration",
    "Modification",
    "ClassModification",
    "ArgumentList",
    "Argument",
    "ElementModificationOrReplaceable",
    "ElementModification",
    "ElementRedeclaration",
    "ElementReplaceable",
    "ComponentClause1",
    "ComponentDecl1",
    "EquationSection",
    "AlgorithmSection",
    "Equation",
    "Statement",
    "IfEquation",
    "IfStatement",
    "ForEquation",
    "ForStatement",
    "ForIndices",
    "ForIndex",
    "WhileStatement",
    "WhenEquation",
    "WhenStatement",
    "ConnectClause",
    "Expression",
    "SimpleExpression",
    "LogicalExpression",
    "LogicalTerm",
    "LogicalFactor",
    "Relation",
    "ArithmeticExpression",
    "Term",
    "Factor",
    "Primary",
    "ComponentRef",
    "FunctionCallArgs",
    "FunctionArguments",
    "NamedArgument",
    "Subscript",
    "Comment",
    "Annotation",
  };
}
/* JavaCC - OriginalChecksum=5d58c70dec37ca342d8d1b78e110d2f7 (do not edit this line) */
