/* Generated By:JJTree: Do not edit this line. OMAnnotation.java */

package com.infoscient.proteus.modelica.parser;

public class OMAnnotation extends SimpleNode {

	public OMClassModification classModification;

	public OMAnnotation(int id) {
		super(id);
	}

	public OMAnnotation(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append("annotation" + classModification.toCode());
		return sb.toString();
	}
	//	
	// public OMAnnotation copy() {
	// OMAnnotation copy = new OMAnnotation(parser, id);
	// copy.classModification = (OMClassModification) classModification.copy();
	// return copy;
	// }
}
