/* Generated By:JJTree: Do not edit this line. OMComponentRef.java */

package com.infoscient.proteus.modelica.parser;

import com.infoscient.proteus.types.StringType;

public class OMComponentRef extends SimpleNode {

	@StringType(name = "String", category = CATEGORY_CODE, description = "Name")
	public String name;

	public OMSubscript[] arraySubscripts;

	public OMComponentRef next;

	public OMComponentRef(int id) {
		super(id);
	}

	public OMComponentRef(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(name);
		if (arraySubscripts != null) {
			sb.append("[");
			int i = 0;
			for (OMSubscript s : arraySubscripts) {
				if (i > 0) {
					sb.append(", ");
				}
				sb.append(s.toCode());
			}
			sb.append("] ");
		}
		if (next != null) {
			sb.append("." + next.toCode());
		}
		return sb.toString();
	}
	//
	// public OMComponentRef copy() {
	// OMComponentRef copy = new OMComponentRef(parser, id);
	// copy.name = name;
	// if (arraySubscripts != null) {
	// copy.arraySubscripts = new OMSubscript[arraySubscripts.length];
	// for (int i = 0; i < arraySubscripts.length; i++) {
	// copy.arraySubscripts[i] = arraySubscripts[i].copy();
	// }
	// }
	// if (next != null) {
	// copy.next = next.copy();
	// }
	// return copy;
	// }
}
