/* Generated By:JJTree: Do not edit this line. OMComponentDecl1.java */

package com.infoscient.proteus.modelica.parser;

public class OMComponentDecl1 extends SimpleNode {

	public OMDeclaration decl;

	public OMComment comment;

	public OMComponentDecl1(int id) {
		super(id);
	}

	public OMComponentDecl1(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(decl.toCode());
		sb.append(comment.toCode());
		return sb.toString();
	}
	//	
	// public OMComponentDecl1 copy() {
	// OMComponentDecl1 copy = new OMComponentDecl1(parser, id);
	// copy.decl = decl.copy();
	// copy.comment = comment.copy();
	// return copy;
	// }
}
