/* Generated By:JJTree: Do not edit this line. OMDeclaration.java */

package com.infoscient.proteus.modelica.parser;

import com.infoscient.proteus.types.StringType;

public class OMDeclaration extends SimpleNode {

	@StringType(name = "Name", category = CATEGORY_CODE)
	public String name;

	public OMModification modification;

	public OMSubscript[] arraySubscripts;

	public OMDeclaration(int id) {
		super(id);
	}

	public OMDeclaration(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(name + " ");
		if (arraySubscripts != null) {
			sb.append("[");
			int i = 0;
			for (OMSubscript s : arraySubscripts) {
				if (i > 0) {
					sb.append(", ");
				}
				sb.append(s.toCode());
			}
			sb.append("] ");
		}
		if (modification != null) {
			sb.append(modification.toCode());
		}
		return sb.toString();
	}
}
