/* Generated By:JJTree: Do not edit this line. OMRelation.java */

package com.infoscient.proteus.modelica.parser;

public class OMRelation extends SimpleNode {

	public OMArithmeticExpression arithmeticExpression1;
		
	public String relOp;

	public OMArithmeticExpression arithmeticExpression2;

	public OMRelation(int id) {
		super(id);
	}

	public OMRelation(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(arithmeticExpression1.toCode());
		if (relOp != null) {
			sb.append(" " + relOp + " ");
			sb.append(arithmeticExpression2.toCode());
		}
		return sb.toString();
	}
}
