/* Generated By:JJTree: Do not edit this line. OMSimpleExpression.java */

package com.infoscient.proteus.modelica.parser;

public class OMSimpleExpression extends SimpleNode {

	public OMLogicalExpression logicalExpression;

	public OMLogicalExpression logicalExpression1;

	public OMLogicalExpression logicalExpression2;

	public OMSimpleExpression(int id) {
		super(id);
	}

	public OMSimpleExpression(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(logicalExpression.toCode());
		 
		if (logicalExpression1 != null) { 
			sb.append(" : " + logicalExpression1.toCode());
			if (logicalExpression2 != null) {
				sb.append(" : " + logicalExpression2.toCode());
			}
		}
		return sb.toString();
	}
}
