/* Generated By:JJTree: Do not edit this line. OMWhileStatement.java */

package com.infoscient.proteus.modelica.parser;

import java.util.LinkedList;
import java.util.List;

public class OMWhileStatement extends SimpleNode {

	public OMExpression whileExpression;

	public List<OMStatement> statements = new LinkedList<OMStatement>();

	public OMWhileStatement(int id) {
		super(id);
	}

	public OMWhileStatement(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append("while " + whileExpression.toCode() + "then\n");
		for (OMStatement s : statements) {
			sb.append(s.toCode() + ";\n");
		}
		sb.append("end while\n");
		return sb.toString();
	}
}
