/* Generated By:JJTree: Do not edit this line. OMComponentDecl.java */

package proteus.gwt.shared.modelica.parser;

public class OMComponentDecl extends SimpleNode {

	public OMDeclaration decl;

	public OMCondAttr condAttr;

	public OMComment comment;

	public OMComponentDecl(int id) {
		super(id);
	}

	public OMComponentDecl(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(decl.toCode());
		if (condAttr != null) {
			sb.append(condAttr.toCode());
		}
		sb.append(comment.toCode());
		return sb.toString();
	}
	//	
	// public OMComponentDecl copy() {
	// OMComponentDecl copy = new OMComponentDecl(parser, id);
	// copy.decl = decl.copy();
	// if (condAttr != null) {
	// copy.condAttr = condAttr.copy();
	// }
	// copy.comment = comment.copy();
	// return copy;
	// }

	public OMDeclaration getDecl() {
		return decl;
	}

	public void setDecl(OMDeclaration decl) {
		this.decl = decl;
	}
}
