/* Generated By:JJTree: Do not edit this line. OMConnectClause.java */

package proteus.gwt.shared.modelica.parser;

public class OMConnectClause extends SimpleNode {

	public OMComponentRef src;

	public OMComponentRef dest;

	public OMConnectClause(int id) {
		super(id);
	}

	public OMConnectClause(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append("connect (" + src.toCode() + ", " + dest.toCode() + ")");
		return sb.toString();
	}
	//	
	// public OMConnectClause copy() {
	// OMConnectClause copy = new OMConnectClause(parser, id);
	// copy.src = src.copy();
	// copy.dest = dest.copy();
	// return copy;
	// }
}
