/* Generated By:JJTree: Do not edit this line. OMElement.java */

package proteus.gwt.shared.modelica.parser;




public class OMElement extends SimpleNode {

	public OMImportClause importClause;

	public OMExtendsClause extendsClause;
	
//	@EnumType(name = "AccessControl", allowed = {"public",
//	"protected" }, category = CATEGORY_CODE)
public String protected_;

//	@BooleanType(name = "Redeclare", category = CATEGORY_CODE)
	public String redeclare;

//	@BooleanType(name = "Final", category = CATEGORY_CODE)
	public String final_;

//	@BooleanType(name = "Inner", category = CATEGORY_CODE)
	public String  typing;

//	@BooleanType(name = "Outer", category = CATEGORY_CODE)
//	public String outer;

//	@BooleanType(name = "Replaceable", category = CATEGORY_CODE)
	public String replaceable;

	public OMClassDefinition classDefinition;

	public OMComponentClause componentClause;

	public OMConstrainingClause constrainingClause;

	public OMComment comment;

	public OMElement(int id) {
		super(id);
	}

	public OMElement(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toCode() {
		StringBuilder sb = new StringBuilder();
		if (importClause != null) {
			sb.append(importClause.toCode());
		} else if (extendsClause != null) {
			sb.append(extendsClause.toCode());
		} else {
			if (final_!=null) {
				sb.append("final ");
			}
			if (typing!=null) {
				sb.append(typing+" ");
			}
			if (classDefinition != null) {
				sb.append(classDefinition.toCode());
			} else if (componentClause != null) {
				sb.append(componentClause.toCode());
			}
		}
		return sb.toString();
	}
}
