/* Generated By:JJTree: Do not edit this line. OMElementList.java */

package proteus.gwt.shared.modelica.parser;

import java.util.LinkedList;
import java.util.List;

public class OMElementList extends SimpleNode {

	public List<OMElement> elements = new LinkedList<OMElement>();

	public List<OMAnnotation> annotations = new LinkedList<OMAnnotation>();

	public OMElementList(int id) {
		super(id);
	}

	public OMElementList(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toCode() {
		StringBuilder sb = new StringBuilder();
		for (OMElement e : elements) {
			sb.append("   "+e.toCode() + ";\n");
		}
		if (!noAnnotation) {
			for (OMAnnotation a : annotations) {
				sb.append(a.toCode() + ";\n");
			}
		}
		return sb.toString();
	}
}
