/* Generated By:JJTree: Do not edit this line. OMEnumList.java */

package proteus.gwt.shared.modelica.parser;

import java.util.LinkedList;
import java.util.List;

public class OMEnumList extends SimpleNode {

	public List<OMEnumLiteral> enumList = new LinkedList<OMEnumLiteral>();

	public OMEnumList(int id) {
		super(id);
	}

	public OMEnumList(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}
}
