/* Generated By:JJTree: Do not edit this line. OMFactor.java */

package proteus.gwt.shared.modelica.parser;

public class OMFactor extends SimpleNode {

	public OMPrimary primary;

	public String op;

	public OMPrimary rhsPrimary;

	public OMFactor(int id) {
		super(id);
	}

	public OMFactor(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(primary.toCode());
		if (op != null) {
			sb.append(" " + op + " ");
			sb.append(rhsPrimary.toCode());
		}
		return sb.toString();
	}
}
