/* Generated By:JJTree: Do not edit this line. OMLogicalFactor.java */

package proteus.gwt.shared.modelica.parser;

public class OMLogicalFactor extends SimpleNode {

	public boolean not;

	public OMRelation relation;

	public OMLogicalFactor(int id) {
		super(id);
	}

	public OMLogicalFactor(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toCode() {
		StringBuilder sb = new StringBuilder();
		if (not) {
			sb.append("not ");
		}
		sb.append(relation.toCode());
		return sb.toString();
	}
}
