/* Generated By:JJTree: Do not edit this line. OMTerm.java */

package proteus.gwt.shared.modelica.parser;

import java.util.LinkedList;
import java.util.List;

public class OMTerm extends SimpleNode {

	public OMFactor factor;

	public List<String> mulOps = new LinkedList<String>();

	public List<OMFactor> rhsFactors = new LinkedList<OMFactor>();
	

	public OMTerm(int id) {
		super(id);
	}

	public OMTerm(ModelicaParser p, int id) {
		super(p, id);
	}

	/** Accept the visitor. * */
	@Override
	public Object jjtAccept(ModelicaParserVisitor visitor, Object data) {
		return visitor.visit(this, data);
	}

	@Override
	public String toCode() {
		StringBuilder sb = new StringBuilder();
		sb.append(factor.toCode());
		int i = 0;
		for (String op : mulOps) {
			sb.append(" " + op + " ");
			sb.append(rhsFactors.get(i++).toCode());
		}
		return sb.toString();
	}
}
